name: cron_e2e_test

on:
  schedule:
    # 2:12, 15:12 UTC daily - inconspicuous times to hopefully prevent service from blocklisting the account
    - cron: '12 2/13 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install modules
      run: npm install
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        MYQ_EMAIL: ${{ secrets.MYQ_EMAIL }}
        MYQ_PASSWORD: ${{ secrets.MYQ_PASSWORD }}
